enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
